<?php require_once './templates/header.phtml' ?>

<form method='POST' action='prestador-edited/<?= $prestador->prestadorId ?>'>
  <div class="form-group">
    <label for="nombrePrestador">Nombre</label>
    <input type="text" class="form-control" id="nombrePrestador" name='nombrePrestador' placeholder="Nombre del prestador" value='<?= $prestador->nombrePrestador ?>'>
  </div>
  <div class="form-group">
    <label for="fechaCreacion">Fecha de creación</label>
    <input type="date" class="form-control" id="fechaCreacion" name='fechaCreacion' placeholder="Fecha de creación" value='<?= $prestador->fechaCreacion ?>'>
  </div>
  <div class="form-group">
    <label for="origen">Origen</label>
    <input type="text" class="form-control" id="origen" name='origen' placeholder="País de procedencia" value='<?= $prestador->origen ?>'>
  </div>
  <button type="submit" class="btn btn-primary">Editar</button>
</form>

<?php require_once './templates/footer.phtml' ?>